### PR TITLE
remove non ascii from filename to avoid error

### LINKED ISSUE #485: The filename fallback must only contain ASCII characters.
Following bug was found in CA log
```
@ingestionTime | 1643710475396
@log | 999702998355:/aws/eks/edlib-eks-q0GvjhDG/logs
@logStream | fluentbit-kube.var.log.containers.contentauthor-c89c466f8-8pd8t_edlib_phpfpm-339b6977c038b45941a31decfe27b4df8718e865f56b9e3898d68a2552c9f231.log
@timestamp | 1643710472551
data.channel | production
data.context.exception.class | InvalidArgumentException
data.context.exception.code | 0
data.context.exception.file | /app/vendor/symfony/http-foundation/HeaderUtils.php:175
data.context.exception.message | The filename fallback must only contain ASCII characters.
data.context.exception.trace.0 | /app/vendor/symfony/http-foundation/ResponseHeaderBag.php:252
data.context.exception.trace.1 | /app/app/Http/Controllers/ContentAssetController.php:37
data.context.exception.trace.2 | /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:48
data.context.exception.trace.3 | /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:262
data.context.exception.trace.4 | /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205
data.context.exception.trace.5 | /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:695
data.context.exception.trace.6 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
data.context.exception.trace.7 | /app/app/Http/Middleware/AdapterMode.php:38
data.context.exception.trace.8 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.9 | /app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50
data.context.exception.trace.10 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.11 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78
data.context.exception.trace.12 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.13 | /app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
data.context.exception.trace.14 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.15 | /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121
data.context.exception.trace.16 | /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64
data.context.exception.trace.17 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.18 | /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
data.context.exception.trace.19 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.20 | /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67
data.context.exception.trace.21 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.22 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
data.context.exception.trace.23 | /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:697
data.context.exception.trace.24 | /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:672
data.context.exception.trace.25 | /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636
data.context.exception.trace.26 | /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:625
data.context.exception.trace.27 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167
data.context.exception.trace.28 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
data.context.exception.trace.29 | /app/app/Http/Middleware/RequestId.php:29
data.context.exception.trace.30 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.31 | /app/vendor/fideloper/proxy/src/TrustProxies.php:57
data.context.exception.trace.32 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.33 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
data.context.exception.trace.34 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31
data.context.exception.trace.35 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.36 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
data.context.exception.trace.37 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40
data.context.exception.trace.38 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.39 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
data.context.exception.trace.40 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.41 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86
data.context.exception.trace.42 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167
data.context.exception.trace.43 | /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
data.context.exception.trace.44 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:142
data.context.exception.trace.45 | /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111
data.context.exception.trace.46 | /app/public/index.php:54
data.datetime | 2022-02-01T10:14:32.549845+00:00
data.level | 400
data.level_name | ERROR
data.message | The filename fallback must only contain ASCII characters.
kubernetes.annotations.kubernetes.io/psp | eks.privileged
kubernetes.container_hash | public.ecr.aws/f0t8l9h1/api-contentauthor-phpfpm@sha256:4f0bb4d4f7a8a478370d152f5402a226f6cef3440c077861fef88d206182c82d
kubernetes.container_image | public.ecr.aws/f0t8l9h1/api-contentauthor-phpfpm:1.11.1
kubernetes.container_name | phpfpm
kubernetes.docker_id | 339b6977c038b45941a31decfe27b4df8718e865f56b9e3898d68a2552c9f231
kubernetes.host | ip-10-5-1-207.eu-west-1.compute.internal
kubernetes.labels.app | contentauthor
kubernetes.labels.fluentd-parser | laravel-json
kubernetes.labels.pod-template-hash | c89c466f8
kubernetes.namespace_name | edlib
kubernetes.pod_id | 3dd63019-cbe6-4504-8d87-01c7a89d8991
kubernetes.pod_name | contentauthor-c89c466f8-8pd8t
log | {"message":"The filename fallback must only contain ASCII characters.","context":{"exception":{"class":"InvalidArgumentException","message":"The filename fallback must only contain ASCII characters.","code":0,"file":"/app/vendor/symfony/http-foundation/HeaderUtils.php:175","trace":["/app/vendor/symfony/http-foundation/ResponseHeaderBag.php:252","/app/app/Http/Controllers/ContentAssetController.php:37","/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:48","/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:262","/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205","/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:695","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128","/app/app/Http/Middleware/AdapterMode.php:38","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121","/app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103","/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:697","/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:672","/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636","/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:625","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128","/app/app/Http/Middleware/RequestId.php:29","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/fideloper/proxy/src/TrustProxies.php:57","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167","/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:142","/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111","/app/public/index.php:54"]}},"level":400,"level_name":"ERROR","channel":"production","datetime":"2022-02-01T10:14:32.549845+00:00","extra":{}}
log_level | error
message | The filename fallback must only contain ASCII characters.
parser.actual_parser | laravel-json
parser.original_parser | laravel-json
stream | stderr
time | 2022-02-01T10:14:32.551306012Z


```

### PR DESCRIPTION
**Pull request by maxmoeschinger**
Fixes #485

### CODE REVIEW

File: sourcecode/apis/contentauthor/app/Http/Controllers/ContentAssetController.php [hunk 1]
```diff
@@ -23,10 +23,10 @@ public function __invoke($path, Request $request)
         if (!$this->contentAuthorStorage->getBucketDisk()->exists($path)) {
             throw new NotFoundHttpException('File not found');
         }
-        
+
         $detector = new FinfoMimeTypeDetector();
         $response = new StreamedResponse;
-        $filename = basename($path);
+        $filename = preg_replace('/[\x00-\x1F\x80-\xFF]/', '', basename($path));
```
Comment (emmachughes) [inline sourcecode/apis/contentauthor/app/Http/Controllers/ContentAssetController.php:29]: Should include \x7f too, as this is a control character (DEL).

Comment (maxmoeschinger) [reply sourcecode/apis/contentauthor/app/Http/Controllers/ContentAssetController.php:29]: so `/[\x00-\x1F\x80-\xFF-\x7f]/`?

Comment (emmachughes) [reply sourcecode/apis/contentauthor/app/Http/Controllers/ContentAssetController.php:29]: `/[\x00-\x1F\x7F-\xFF]/`

**Review by emmachughes — APPROVED** [review]
