### PR TITLE
Ensure all authors are inserted

### LINKED ISSUE #279: NDLA H5P: Video from API is missing data in Rights of use
**Missing attribution data**
Inserted video from API (Brightcove) is missing attribution data. 
We need to 1. verify that all attribution data is received from the video API 2. if yes, make sure all is displayed.

**To Reproduce**

1. Add video "Atferd hos dyr" from Brightcove to Course Presentation or interactive video. 
2. Add the same video to an article "standalone"
3. Compare attribution
4. Verify that all attribution is received: 

Copied source of attributon:
Forfatter: Ragnhild Baglo, Forfatter: Kristin Bøhle, Forfatter: Einar Berg, Forfatter: Alf Jacob Nilsen. Atferd hos dyr [Internett]. Leverandør: Amendor AS. Hentet fra: https://players.brightcove.net/4806596774001/BkLm8fT_default/index.html?videoId=5796599604001

**Expected behavior**
Rights of use should contain all authors and attributed persons.

**Screenshots**
Skjermbilde 2021-12-02 kl  15 17 44
Skjermbilde 2021-12-02 kl  15 35 52

### PR DESCRIPTION
**Pull request by maxmoeschinger**
Fixes #279

### CODE REVIEW

File: sourcecode/apis/contentauthor/public/js/h5p/ndla-contentbrowser.js [hunk 1]
```diff
@@ -546,12 +546,28 @@ class VideoBrowser extends ContentBrowserBase {
             }
         }
 
-        if (ContentBrowserBase.checkNestedRequirements(values, 'values.custom_fields.licenseinfo')) {
-            copyRight.authors.push({ name: values.custom_fields.licenseinfo });
-        }
-        if (ContentBrowserBase.checkNestedRequirements(values, 'values.custom_fields.licenseinfo2')) {
-            copyRight.authors.push({ name: values.custom_fields.licenseinfo2 });
+        const maxDepth = 20;
+        let run = true;
```
Comment (emmachughes) [inline sourcecode/apis/contentauthor/public/js/h5p/ndla-contentbrowser.js:550]: Could be simplified as a do-while loop.

**Review by emmachughes — APPROVED** [review]
